export { default as LoginScreen} from "./Login"
export { default as CadastrarScreen} from "./Cadastrar"
export { default as PerfilScreen} from "./Perfil"
export { default as CultivosScreen} from "./Cultivos"
export { default as ScrollScreen} from "./IntroScroll"
export { default as SairScreen} from "./Sair"
export { default as CalcScreen} from "./Calculadora"
export { default as EditarPerfilScreen} from "./EditarPerfil"